# Generated by Django 4.1.6 on 2023-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='position',
            field=models.CharField(default='توسعه دهنده بک اند', max_length=50),
        ),
    ]
