# Generated by Django 4.1.6 on 2023-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_working_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduction',
            name='position',
            field=models.CharField(default='کارشناسی کامپیوتر', max_length=50),
        ),
    ]
