# Generated by Django 4.1.6 on 2023-02-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_eduction_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us',
            new_name='Coutact_us',
        ),
    ]
